package com.phoenix.phnx.identity

import android.content.Context
import android.content.res.Configuration
import android.os.Build
import android.webkit.WebSettings
import java.util.Locale
import java.util.TimeZone

data class DevicePreset(
    val id: String,
    val name: String,
    val operatingSystem: String,
    val platform: String,
    val userAgent: String,
    val viewportWidth: Int,
    val viewportHeight: Int,
    val screenWidth: Int,
    val screenHeight: Int,
    val colorDepth: Int,
    val deviceScaleFactor: Double,
    val locale: String,
    val language: String,
    val languages: List<String>,
    val timezone: String,
    val touchSupport: Boolean,
    val mobileMode: Boolean,
    val clientHints: ClientHintsConfig,
) {
    fun forProfile(profileId: String) = BrowserIdentityConfig(
        profileId = profileId,
        presetId = id,
        userAgent = userAgent,
        platform = platform,
        operatingSystem = operatingSystem,
        viewportWidth = viewportWidth,
        viewportHeight = viewportHeight,
        screenWidth = screenWidth,
        screenHeight = screenHeight,
        colorDepth = colorDepth,
        deviceScaleFactor = deviceScaleFactor,
        locale = locale,
        language = language,
        languages = languages,
        timezone = timezone,
        touchSupport = touchSupport,
        mobileMode = mobileMode,
        clientHints = clientHints,
    )
}

object DevicePresets {
    const val SYSTEM_DEFAULT = "system_default"
    const val ANDROID_PHONE = "android_phone"
    const val GALAXY_S24 = "galaxy_s24"
    const val ONEPLUS_12 = "oneplus_12"
    const val XIAOMI_14 = "xiaomi_14"
    const val ANDROID_TABLET = "android_tablet"
    const val IPHONE_15 = "iphone_15"
    const val IPAD_PRO = "ipad_pro"
    const val DESKTOP = "desktop"
    const val MACBOOK_PRO = "macbook_pro"
    const val LINUX_DESKTOP = "linux_desktop"

    private val presets = listOf(
        DevicePreset(
            id = ANDROID_PHONE,
            name = "Google Pixel 8",
            operatingSystem = "Android 14",
            platform = "Android",
            userAgent = "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
            viewportWidth = 412,
            viewportHeight = 915,
            screenWidth = 1080,
            screenHeight = 2400,
            colorDepth = 24,
            deviceScaleFactor = 2.625,
            locale = "en-US",
            language = "en-US",
            languages = listOf("en-US", "en"),
            timezone = "America/New_York",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("Android", true, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = GALAXY_S24,
            name = "Samsung Galaxy S24",
            operatingSystem = "Android 14",
            platform = "Android",
            userAgent = "Mozilla/5.0 (Linux; Android 14; SM-S921B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
            viewportWidth = 360,
            viewportHeight = 780,
            screenWidth = 1080,
            screenHeight = 2340,
            colorDepth = 24,
            deviceScaleFactor = 3.0,
            locale = "en-GB",
            language = "en-GB",
            languages = listOf("en-GB", "en"),
            timezone = "Europe/London",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("Android", true, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = ONEPLUS_12,
            name = "OnePlus 12",
            operatingSystem = "Android 14",
            platform = "Android",
            userAgent = "Mozilla/5.0 (Linux; Android 14; CPH2573) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
            viewportWidth = 412,
            viewportHeight = 906,
            screenWidth = 1440,
            screenHeight = 3168,
            colorDepth = 24,
            deviceScaleFactor = 3.5,
            locale = "en-IN",
            language = "en-IN",
            languages = listOf("en-IN", "en"),
            timezone = "Asia/Kolkata",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("Android", true, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = XIAOMI_14,
            name = "Xiaomi 14",
            operatingSystem = "Android 14",
            platform = "Android",
            userAgent = "Mozilla/5.0 (Linux; Android 14; 23127PN0CC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36",
            viewportWidth = 400,
            viewportHeight = 890,
            screenWidth = 1200,
            screenHeight = 2670,
            colorDepth = 24,
            deviceScaleFactor = 3.0,
            locale = "zh-CN",
            language = "zh-CN",
            languages = listOf("zh-CN", "zh", "en-US"),
            timezone = "Asia/Shanghai",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("Android", true, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = ANDROID_TABLET,
            name = "Google Pixel Tablet",
            operatingSystem = "Android 14",
            platform = "Android",
            userAgent = "Mozilla/5.0 (Linux; Android 14; Pixel Tablet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            viewportWidth = 1280,
            viewportHeight = 800,
            screenWidth = 2560,
            screenHeight = 1600,
            colorDepth = 24,
            deviceScaleFactor = 2.0,
            locale = "en-US",
            language = "en-US",
            languages = listOf("en-US", "en"),
            timezone = "America/New_York",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("Android", true, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = IPHONE_15,
            name = "Apple iPhone 15",
            operatingSystem = "iOS 17",
            platform = "iOS",
            userAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1",
            viewportWidth = 393,
            viewportHeight = 852,
            screenWidth = 1179,
            screenHeight = 2556,
            colorDepth = 24,
            deviceScaleFactor = 3.0,
            locale = "en-US",
            language = "en-US",
            languages = listOf("en-US", "en"),
            timezone = "America/Los_Angeles",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("iOS", true, listOf("Safari")),
        ),
        DevicePreset(
            id = IPAD_PRO,
            name = "Apple iPad Pro 12.9",
            operatingSystem = "iPadOS 17",
            platform = "iOS",
            userAgent = "Mozilla/5.0 (iPad; CPU OS 17_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Mobile/15E148 Safari/604.1",
            viewportWidth = 1024,
            viewportHeight = 1366,
            screenWidth = 2048,
            screenHeight = 2732,
            colorDepth = 24,
            deviceScaleFactor = 2.0,
            locale = "en-GB",
            language = "en-GB",
            languages = listOf("en-GB", "en"),
            timezone = "Europe/London",
            touchSupport = true,
            mobileMode = true,
            clientHints = ClientHintsConfig("iOS", true, listOf("Safari")),
        ),
        DevicePreset(
            id = DESKTOP,
            name = "Windows 11 Desktop",
            operatingSystem = "Windows 11",
            platform = "Windows",
            userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            viewportWidth = 1440,
            viewportHeight = 900,
            screenWidth = 1920,
            screenHeight = 1080,
            colorDepth = 24,
            deviceScaleFactor = 1.0,
            locale = "en-US",
            language = "en-US",
            languages = listOf("en-US", "en"),
            timezone = "America/New_York",
            touchSupport = false,
            mobileMode = false,
            clientHints = ClientHintsConfig("Windows", false, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = MACBOOK_PRO,
            name = "MacBook Pro 14",
            operatingSystem = "macOS 14",
            platform = "macOS",
            userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            viewportWidth = 1512,
            viewportHeight = 982,
            screenWidth = 3024,
            screenHeight = 1964,
            colorDepth = 24,
            deviceScaleFactor = 2.0,
            locale = "en-US",
            language = "en-US",
            languages = listOf("en-US", "en"),
            timezone = "America/Los_Angeles",
            touchSupport = false,
            mobileMode = false,
            clientHints = ClientHintsConfig("macOS", false, listOf("Chromium", "Google Chrome")),
        ),
        DevicePreset(
            id = LINUX_DESKTOP,
            name = "Linux Desktop",
            operatingSystem = "Linux",
            platform = "Linux",
            userAgent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
            viewportWidth = 1366,
            viewportHeight = 768,
            screenWidth = 1366,
            screenHeight = 768,
            colorDepth = 24,
            deviceScaleFactor = 1.0,
            locale = "de-DE",
            language = "de-DE",
            languages = listOf("de-DE", "de", "en-US"),
            timezone = "Europe/Berlin",
            touchSupport = false,
            mobileMode = false,
            clientHints = ClientHintsConfig("Linux", false, listOf("Chromium", "Google Chrome")),
        ),
    )

    fun all(): List<DevicePreset> = presets

    fun get(id: String): DevicePreset? = presets.firstOrNull { it.id == id }

    fun default(): DevicePreset = presets.first()

    fun systemDefault(context: Context): DevicePreset {
        val metrics = context.resources.displayMetrics
        val languageTags = context.resources.configuration.locales.toLanguageTags()
            .ifBlank { Locale.getDefault().toLanguageTag() }
            .split(',')
            .filter(String::isNotBlank)
        val primaryLanguage = languageTags.firstOrNull() ?: Locale.getDefault().toLanguageTag()
        val isTouch = context.resources.configuration.touchscreen != Configuration.TOUCHSCREEN_NOTOUCH
        return DevicePreset(
            id = SYSTEM_DEFAULT,
            name = "System Default",
            operatingSystem = "Android ${Build.VERSION.RELEASE}",
            platform = "Android",
            userAgent = WebSettings.getDefaultUserAgent(context),
            viewportWidth = (metrics.widthPixels / metrics.density).toInt().coerceAtLeast(1),
            viewportHeight = (metrics.heightPixels / metrics.density).toInt().coerceAtLeast(1),
            screenWidth = metrics.widthPixels.coerceAtLeast(1),
            screenHeight = metrics.heightPixels.coerceAtLeast(1),
            colorDepth = 24,
            deviceScaleFactor = metrics.density.toDouble().coerceIn(0.5, 4.0),
            locale = primaryLanguage,
            language = primaryLanguage,
            languages = languageTags,
            timezone = TimeZone.getDefault().id,
            touchSupport = isTouch,
            mobileMode = isTouch,
            clientHints = ClientHintsConfig("Android", isTouch, listOf("Chromium", "Google Chrome")),
        )
    }
}
